### ISSUE TITLE
Error during training 

### ISSUE THREAD

**Issue by Toettrup** [VisualComputingInstitute/TrackR-CNN#107]
Hello,
Thanks for sharing your code, appreciate it a lot. 
I want in the future to train on my own data, but first I'll try to just train a model on your dataset as you described in the Readme file. 
Im working on a RTX2060 GPU, which gives an error caused by excessive memory usage. So, for that reason I have lowered the batch size in the config file under #training settings from 8 to 5, but then I get another error due to: 
"indices[15] = [15, 1] does not index into param shape [16,1,4]"
Do I have to change the batch size in other places than just the config file, or does this implementation work specifically with a bath size of 8? 
Thanks for the reply in advance! :)

**Comment by ahnonay** [comment]
Hi, unfortunately, we did not try to make the implementation work with all batch sizes. You might try some other ones and see if that helps. Then again, the batch size should not be much smaller so that the 3dconvs can still learn some temporal context. If you have excessive memory usage, it might help to decrease the input image size.

**Comment by ahnonay** [comment]
Closing for now, please reopen if needed
