### ISSUE TITLE
some questions about conv3D

### ISSUE THREAD

**Issue by lcyawym** [VisualComputingInstitute/TrackR-CNN#41]
1.I see the old_order of layers.If order,dropout -> conv -> batchnorm -> activation -> pool, can you tell me why you chage the order?
2.There are two conv3D in your networks. Are these two networks connected in series or in parallel？

**Comment by pvoigtlaender** [comment]
Hi,

1. in other works different orders have been used. Our implementation was kept flexible so that we can do both. For TrackR-CNN we made it consistent with the TensorPack implementation.
2. I'm not entirely sure what you mean with "in series" or "in parallel". You can think of it as the whole sequence (chunk) goes through the first 3d conv layer which outputs a new sequence which is then send to the next 3d conv layer.

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
