### ISSUE TITLE
Training or finetuning on custom dataset

### ISSUE THREAD

**Issue by Tathagatd96** [VisualComputingInstitute/TrackR-CNN#80]
I was wondering if there was a more verbose tutorial for training or finetuning TrackR-CNN on my own custom dataset.

**Comment by pvoigtlaender** [comment]
Sorry, we didn't create a verbose tutorial. The easiest might be to make your own data look like KITTI MOTS (give it the same format), and then set "KITTI_segtrack_data_dir" to point to your dataset.
You can use 
`"load_init":` "models/conv3d_sep2/conv3d_sep2-00000005",`
to initialize from the KITTI MOTS checkpoint.

**Comment by Tathagatd96** [comment]
Got it. Thanks for the quick reply.

**Comment by XiaoBingCQY** [comment]
@pvoigtlaender Sorry,I have some problems,there are three files of conv3d_sep2_sep2-00005 in models,they are 'conv3d_sep2_sep2-00005.data-00000-of-00001','conv3d_sep2_sep2-00005.index','conv3d_sep2_sep2-00005.meta' respectively.So which one should I use?
And when I run 'python main.py configs/conv3d_sep2',the terminal will show 'starting from epoch 6 and  starting training',nothing happens next.

**Comment by SamihaSara** [comment]
@XiaoBingCQY Have you corrected "load init" in config files? I faced the similar problem. You can have a look at https://github.com/VisualComputingInstitute/TrackR-CNN/issues/79

**Comment by XiaoBingCQY** [comment]
&nbsp; &nbsp; Thanks for you reply.Because there are three files of conv3d_sep2_sep2-00005 in models,they are 'conv3d_sep2_sep2-00005.data-00000-of-00001','conv3d_sep2_sep2-00005.index','conv3d_sep2_sep2-00005.meta' respectively.So i don‘t know use which one.Which one did you use?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisualComputingInstitute/TrackR-CNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 晚上8:42
收件人:&nbsp;"VisualComputingInstitute/TrackR-CNN"<TrackR-CNN@noreply.github.com&gt;;
抄送:&nbsp;"591956503"<591956503@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualComputingInstitute/TrackR-CNN] Training or finetuning on custom dataset (#80)





 
@XiaoBingCQY Have you corrected "load init" in config files?

**Comment by SamihaSara** [comment]
I just corrected load init in config file, and renamed model name, then it began training from epoch 1 (https://github.com/VisualComputingInstitute/TrackR-CNN/issues/57). I think it mainly uses
'conv3d_sep2_sep2-00005.data-00000-of-00001'

**Comment by XiaoBingCQY** [comment]
I know that it need to correct load init in config file,but I found there are many files in models,such as&nbsp;'conv3d_sep2_sep2-00005.data-00000-of-00001','conv3d_sep2_sep2-00005.index','conv3d_sep2_sep2-00005.meta',so i don't know which one should be used.And I don't understand that how are you renamed model name.Can you&nbsp;describe it in detail.Thank you very much.
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "VisualComputingInstitute/TrackR-CNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 晚上9:40
收件人:&nbsp;"VisualComputingInstitute/TrackR-CNN"<TrackR-CNN@noreply.github.com&gt;;
抄送:&nbsp;"591956503"<591956503@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualComputingInstitute/TrackR-CNN] Training or finetuning on custom dataset (#80)





 
I just corrected load init in config file, and renamed model name, then it began training from epoch 1.

**Comment by SamihaSara** [comment]
@XiaoBingCQY have you followed this step https://github.com/VisualComputingInstitute/TrackR-CNN#folder-structure-and-config-flags?
If yes, then rename the model field in all config files, 

{
   Engine settings
  "model": "conv3d_batch_all",   // change this name 
}

and  try this in config files ->  "load_init": "models/conv3d_sep2/conv3d_sep2-00000005"
 You do not have to select one of these 3 files 'conv3d_sep2_sep2-00005.data-00000-of-00001','conv3d_sep2_sep2-00005.index','conv3d_sep2_sep2-00005.meta'.
Still if it's unclear please have a look at the issues,  this problem was solved before. 
Hope this helps.

**Comment by XiaoBingCQY** [comment]
Oh, I see.Thank you very much.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VisualComputingInstitute/TrackR-CNN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 上午10:18
收件人:&nbsp;"VisualComputingInstitute/TrackR-CNN"<TrackR-CNN@noreply.github.com&gt;;
抄送:&nbsp;"591956503"<591956503@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [VisualComputingInstitute/TrackR-CNN] Training or finetuning on custom dataset (#80)





 
@XiaoBingCQY have you followed this step https://github.com/VisualComputingInstitute/TrackR-CNN#folder-structure-and-config-flags?
 If yes, then rename the model field in all config files,
 
{
 Engine settings
 "model": "conv3d_batch_all",   // change this name
 }
 
and  try this in config files -&gt;  "load_init": "models/conv3d_sep2/conv3d_sep2-00000005"
 You do not have to select one of these 3 files 'conv3d_sep2_sep2-00005.data-00000-of-00001','conv3d_sep2_sep2-00005.index','conv3d_sep2_sep2-00005.meta'.
 Still if it's unclear please have a look at the issues,  some faced this problem before.
 Hope this helps.

**Comment by ahnonay** [comment]
Yes, you can just put all three files into the
`models/conv3d_sep2/`
folder and then create a new config by copying the conv3d_sep2 config and setting
```
"model": "YOUR_MODEL_NAME"
"load_init": "models/conv3d_sep2/conv3d_sep2-00000005",
```

**Comment by ahnonay** [comment]
Closing this for now, please reopen if needed
